### ISSUE TITLE
网络模型转换错误的具体原因能否回溯

### ISSUE THREAD

**Issue by KafCoppelia** [RT-Thread/RT-AIKit-plugin-stm32#15]
对[Yolo-FastestV2](https://github.com/dog-qiuqiu/Yolo-FastestV2)的onnx模型进行转换，报生成错误：

![image](https://user-images.githubusercontent.com/69038090/173213509-7c4fea56-59a9-44f1-92c6-0a09bd57d54d.png)

在`rt_ai_tools`下会生成：

![image](https://user-images.githubusercontent.com/69038090/173213565-cd9c6e38-ab0b-4d13-9c3a-61fb13aa42b8.png)

的确，`X-CUBE-AI\App`下没有任何CUBE AI生成的文件。具体原因可以回溯么（例如，模型的一些网络层不支持）

有关Yolo-FastestV2的网络在其repo`model`下

**Comment by liqiwenx** [comment]
根据报错, 内容来看, 请检查一下参数, 对于一些路径, 检查是否有空格和特殊字符, 如果有, 在路径上加入双引号.
![image](https://user-images.githubusercontent.com/52438879/173271637-23e9a5d2-74de-4d75-abca-0c950cde5fa1.png)

**Comment by KafCoppelia** [comment]
确认了不是路径的问题，上面这行命令，仅改为转换模型`keras_mnist.h5`（repo中的示例模型）则一切顺利

**Comment by pinxue** [comment]
长久没有活动，先关闭了。
